### ISSUE TITLE
Rethinking the License 

### ISSUE THREAD

**Issue by josephdviviano** [GFNOrg/torchgfn#151]
@saleml @vict0rsch 

One important piece of feedback I received at NeurIPS from some potential collaborators at IBM was our license was restrictive. 

I propose we switch to Apache 2.0, in the next release, which will include all current outstanding PRs.

What do you two think?

https://www.mend.io/blog/top-10-apache-license-questions-answered/

**Comment by vict0rsch** [comment]
Yey :) Apache 2.0 is a good option
