### ISSUE TITLE
Hypergrid.get_terminating_states_indices code

### ISSUE THREAD

**Issue by younik** [GFNOrg/torchgfn#205]
I believe this function is not correct; it should be without argument and use `self.sf` (?)

https://github.com/GFNOrg/torchgfn/blob/c62b5b03b7c2cb6c669f2a0623fbe6484995b943/src/gfn/gym/hypergrid.py#L149-L152

**Comment by josephdviviano** [comment]
Yeah, you're right. It's also not used anywhere. I'll submit a patch to remove it.

**Comment by josephdviviano** [comment]
Addressed here -- https://github.com/GFNOrg/torchgfn/pull/217

**Comment by josephdviviano** [comment]
OK - actually, this is fine. It's supposed to return the indices of the final states as sampled. It's used in this file 

https://github.com/GFNOrg/torchgfn/blob/8259a2139ce9ccc22fb2832c45cb2ffb7846314c/src/gfn/utils/training.py#L20

to calculate the `l1_dist` with the true posterior. 

however I'm going to patch up one or two things to make this more obvious and make the tests more robust.

**Comment by josephdviviano** [comment]
I've submitted a PR that hopefully addresses the confusion here.

**Comment by josephdviviano** [comment]
There's no need for this function when it just calls `self.get_states_indices` -- we should simply directly call this.

**Comment by josephdviviano** [comment]
Will follow up in new issue
